import { AppSliceType } from "@/types/store/AppSliceType";
import { createSlice } from "@reduxjs/toolkit";

const initialState: AppSliceType = {
  upcomingAnime: [
    {
      aired: {
        from: "2025-10-01T00:00:00+00:00",
        prop: [Object],
        string: "Oct 2025 to ?",
        to: null,
      },
      airing: false,
      approved: true,
      background: "",
      broadcast: { day: null, string: "Unknown", time: null, timezone: null },
      demographics: [[Object]],
      duration: "Unknown",
      episodes: null,
      explicit_genres: [],
      favorites: 6553,
      genres: [[Object], [Object]],
      images: { jpg: [Object], webp: [Object] },
      licensors: [],
      mal_id: 52807,
      members: 305521,
      popularity: 885,
      producers: [[Object]],
      rank: null,
      rating: "R - 17+ (violence & profanity)",
      score: null,
      scored_by: null,
      season: "fall",
      source: "Manga",
      status: "Not yet aired",
      studios: [[Object]],
      synopsis: "Third season of One Punch Man.",
      themes: [[Object], [Object], [Object]],
      title: "One Punch Man 3",
      title_english: "One Punch Man Season 3",
      title_japanese: "ワンパンマン 3",
      title_synonyms: ["One Punch Man 3rd Season"],
      titles: [[Object], [Object], [Object], [Object]],
      trailer: {
        embed_url:
          "https://www.youtube.com/embed/j1hqIrLqOso?enablejsapi=1&wmode=opaque&autoplay=1",
        images: [Object],
        url: "https://www.youtube.com/watch?v=j1hqIrLqOso",
        youtube_id: "j1hqIrLqOso",
      },
      type: "TV",
      url: "https://myanimelist.net/anime/52807/One_Punch_Man_3",
      year: 2025,
    },
    {
      aired: {
        from: "2026-01-01T00:00:00+00:00",
        prop: [Object],
        string: "Jan 2026 to ?",
        to: null,
      },
      airing: false,
      approved: true,
      background: "",
      broadcast: { day: null, string: "Unknown", time: null, timezone: null },
      demographics: [[Object]],
      duration: "Unknown",
      episodes: null,
      explicit_genres: [],
      favorites: 1616,
      genres: [[Object], [Object], [Object]],
      images: { jpg: [Object], webp: [Object] },
      licensors: [],
      mal_id: 59978,
      members: 183557,
      popularity: 1432,
      producers: [[Object]],
      rank: null,
      rating: "PG-13 - Teens 13 or older",
      score: null,
      scored_by: null,
      season: "winter",
      source: "Manga",
      status: "Not yet aired",
      studios: [[Object]],
      synopsis: "Second season of Sousou no Frieren.",
      themes: [],
      title: "Sousou no Frieren 2nd Season",
      title_english: "Frieren: Beyond Journey's End Season 2",
      title_japanese: "葬送のフリーレン 第2期",
      title_synonyms: ["Frieren at the Funeral Season 2"],
      titles: [[Object], [Object], [Object], [Object]],
      trailer: {
        embed_url:
          "https://www.youtube.com/embed/P-YPtYkViKM?enablejsapi=1&wmode=opaque&autoplay=1",
        images: [Object],
        url: "https://www.youtube.com/watch?v=P-YPtYkViKM",
        youtube_id: "P-YPtYkViKM",
      },
      type: "TV",
      url: "https://myanimelist.net/anime/59978/Sousou_no_Frieren_2nd_Season",
      year: 2026,
    },
    {
      aired: { from: null, prop: [Object], string: "Not available", to: null },
      airing: false,
      approved: true,
      background: "",
      broadcast: { day: null, string: "Unknown", time: null, timezone: null },
      demographics: [],
      duration: "Unknown",
      episodes: null,
      explicit_genres: [],
      favorites: 2748,
      genres: [[Object], [Object]],
      images: { jpg: [Object], webp: [Object] },
      licensors: [],
      mal_id: 49233,
      members: 179610,
      popularity: 1462,
      producers: [[Object]],
      rank: null,
      rating: "R - 17+ (violence & profanity)",
      score: null,
      scored_by: null,
      season: null,
      source: "Light novel",
      status: "Not yet aired",
      studios: [[Object]],
      synopsis: "Second season of Youjo Senki.",
      themes: [[Object], [Object], [Object]],
      title: "Youjo Senki II",
      title_english: "Saga of Tanya the Evil II",
      title_japanese: "幼女戦記 II",
      title_synonyms: [
        "The Military Chronicles of a Little Girl II",
        "Youjo Senki 2nd Season",
      ],
      titles: [[Object], [Object], [Object], [Object], [Object]],
      trailer: {
        embed_url:
          "https://www.youtube.com/embed/v4Uj7RJprQE?enablejsapi=1&wmode=opaque&autoplay=1",
        images: [Object],
        url: "https://www.youtube.com/watch?v=v4Uj7RJprQE",
        youtube_id: "v4Uj7RJprQE",
      },
      type: "TV",
      url: "https://myanimelist.net/anime/49233/Youjo_Senki_II",
      year: null,
    },
    {
      aired: {
        from: "2026-01-01T00:00:00+00:00",
        prop: [Object],
        string: "Jan 2026 to ?",
        to: null,
      },
      airing: false,
      approved: true,
      background: "",
      broadcast: { day: null, string: "Unknown", time: null, timezone: null },
      demographics: [[Object]],
      duration: "Unknown",
      episodes: null,
      explicit_genres: [],
      favorites: 1540,
      genres: [[Object], [Object], [Object]],
      images: { jpg: [Object], webp: [Object] },
      licensors: [],
      mal_id: 55825,
      members: 167952,
      popularity: 1564,
      producers: [[Object]],
      rank: null,
      rating: "R - 17+ (violence & profanity)",
      score: null,
      scored_by: null,
      season: "winter",
      source: "Manga",
      status: "Not yet aired",
      studios: [[Object]],
      synopsis: "Second season of Jigokuraku.",
      themes: [[Object], [Object], [Object]],
      title: "Jigokuraku 2nd Season",
      title_english: "Hell's Paradise Season 2",
      title_japanese: "地獄楽第二期",
      title_synonyms: ["Paradition", "Heavenhell"],
      titles: [[Object], [Object], [Object], [Object], [Object]],
      trailer: {
        embed_url:
          "https://www.youtube.com/embed/QyEDvQFWH3E?enablejsapi=1&wmode=opaque&autoplay=1",
        images: [Object],
        url: "https://www.youtube.com/watch?v=QyEDvQFWH3E",
        youtube_id: "QyEDvQFWH3E",
      },
      type: "TV",
      url: "https://myanimelist.net/anime/55825/Jigokuraku_2nd_Season",
      year: 2026,
    },
    {
      aired: {
        from: "2025-10-01T00:00:00+00:00",
        prop: [Object],
        string: "Oct 2025 to ?",
        to: null,
      },
      airing: false,
      approved: true,
      background: "",
      broadcast: { day: null, string: "Unknown", time: null, timezone: null },
      demographics: [[Object]],
      duration: "Unknown",
      episodes: null,
      explicit_genres: [],
      favorites: 816,
      genres: [[Object], [Object]],
      images: { jpg: [Object], webp: [Object] },
      licensors: [],
      mal_id: 59027,
      members: 154855,
      popularity: 1658,
      producers: [],
      rank: null,
      rating: "PG-13 - Teens 13 or older",
      score: null,
      scored_by: null,
      season: "fall",
      source: "Manga",
      status: "Not yet aired",
      studios: [[Object], [Object]],
      synopsis: "Third season of Spy x Family.",
      themes: [[Object], [Object]],
      title: "Spy x Family Season 3",
      title_english: null,
      title_japanese: "SPY×FAMILY Season 3",
      title_synonyms: [],
      titles: [[Object], [Object]],
      trailer: {
        embed_url:
          "https://www.youtube.com/embed/mdB4IDEHFYk?enablejsapi=1&wmode=opaque&autoplay=1",
        images: [Object],
        url: "https://www.youtube.com/watch?v=mdB4IDEHFYk",
        youtube_id: "mdB4IDEHFYk",
      },
      type: "TV",
      url: "https://myanimelist.net/anime/59027/Spy_x_Family_Season_3",
      year: 2025,
    },
  ],
  ongoinggAnime: [],
  isScrolling: true,
};
const AppSlice = createSlice({
  name: "AppSlice",
  initialState,
  reducers: {
    setUpcomingAnime: (state, action) => {
      state.upcomingAnime = action.payload;
    },
    setIsScrolling: (state, action) => {
      console.log(action.payload);
      state.isScrolling = action.payload;
    },
  },
});

export const AppReducer = AppSlice.reducer;
export const { setUpcomingAnime, setIsScrolling } = AppSlice.actions;
